#!/bin/bash

PROJECT_NAME=$1
HOSTNAME=$2 # Hostname to add/remove.
ETC_HOSTS=/etc/hosts # PATH TO YOUR HOSTS FILE
IP="127.0.0.1" # DEFAULT IP FOR HOSTNAME
INSTALL_DIR=./
PROJECT_REPO=$3

function wellcomeMessage() {
    echo
    echo "Hi. Wellcome to ${PROJECT_NAME} Project"
    echo
}

function validationsBeforeInstall() {
    echo
    echo "   Validating before install ...."
    echo "   ================================================="
    echo
    if [ -z "$(which composer)" ]; then
        echo "   - Composer should be installed! see: (https://getcomposer.org/download/)"; exit 1;
    else
        echo "   - Composer alredy installed Ok."
    fi
    if [ "$(ls -A $INSTALL_DIR)" ]; then
        echo "   - Directory should be empty. Install canceled.";exit 1;
    fill
}

function addhost() {
    echo
    echo "   Configuring /etc/hosts ...."
    echo "   ================================================="
    echo
    HOSTS_LINE="$IP\t$HOSTNAME"
    if [ -n "$(grep $HOSTNAME /etc/hosts)" ]
        then
            echo "   - $HOSTNAME already exists : $(grep $HOSTNAME $ETC_HOSTS)"
        else
            echo "   - Adding $HOSTNAME to your $ETC_HOSTS";
            sudo -- sh -c -e "echo '$HOSTS_LINE' >> /etc/hosts";

            if [ -n "$(grep $HOSTNAME /etc/hosts)" ]
                then
                    echo "       $HOSTNAME was added succesfully: $(grep $HOSTNAME /etc/hosts)";
                else
                    echo "       Failed to Add $HOSTNAME, Try again!";
            fi
    fi
}

function addReposKeys() {
    echo
    echo "   Configuring Magento/Github auth keys ...."
    echo "   ================================================="
    echo

    PUBLIC_KEY="$(composer config -gl | grep '\[http-basic.repo.magento.com.username\]' | cut -c40-)"
    PRIVATE_KEY="$(composer config -gl | grep '\[http-basic.repo.magento.com.password\]' | cut -c40-)"
    GITHUB_KEY="$(composer config -gl | grep '\[github-oauth.github.com\]' | cut -c40-)"

    if [ -z "$PUBLIC_KEY" ] || [ -z "$PRIVATE_KEY" ] || [ -z "$GITHUB_KEY" ]; then
        echo "   - Authentication required (https://marketplace.magento.com/customer/accessKeys/ and https://github.com/settings/tokens):"
        read -p "        Magento Public Key: " PUBLIC_KEY
        read -p "        Magento Private Key: " PRIVATE_KEY
        read -p "        Github Token: " GITHUB_KEY
        echo
        if [ -n "$PUBLIC_KEY" ] && [ -n "$PRIVATE_KEY" ] && [ -n "$GITHUB_KEY" ] && [ ! -z "$(which composer)" ]; then
            composer global config http-basic.repo.magento.com $PUBLIC_KEY $PRIVATE_KEY
            composer global config github-oauth.github.com $GITHUB_KEY
        else 
            echo "        You should fill all authentication fields Magento Public Key, Magento Private Key and Github Token"
        fi
    else
        echo "   - Authentication already configured!"
    fi
}

function install() {
    echo
    echo "   Install ...."
    echo "   ================================================="
    echo
    sudo sysctl -w vm.max_map_count=262144
    curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
    rm -rf src/
    git clone $PROJECT_REPO src/
    bin/setup $HOSTNAME
}

wellcomeMessage
validationsBeforeInstall
addhost
addReposKeys
install